version: '3.9'

volumes:
  postgres_volume:

services:
  pg:
    image: postgres:17.4-alpine3.21
    env_file:
      - .env
    ports:
      - "54322:5432"
    volumes:
      - postgres_volume:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $$POSTGRES_USER" ]
      interval: 3s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - pg
    env_file:
      - .env

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx.crt:/etc/nginx/certs/nginx.crt:ro
      - ./nginx.key:/etc/nginx/certs/nginx.key:ro
    depends_on:
      - backend
