name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

env:
  REGISTRY: "cr.selcloud.ru/vkatun"
  IMAGE_NAME: "vkatun"
  CONTAINER_NAME: "vkatun-container"

jobs:
  run-go-unit-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.24

      - name: Run tests
        run: |
          cd backend
          go mod download
          go test ./... -v

  # пушим в наш registry
  image-build-and-push:
    runs-on: ubuntu-latest
    needs: run-go-unit-tests

    steps:
      - name: Checkout master
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Registry
        # логин и пароль храним в секретах гитхаба
        run: docker login -u ${{ secrets.REGISTRY_USERNAME }} -p ${{ secrets.REGISTRY_PASSWORD }} $REGISTRY

      - name: Build and Push Docker Image
        # многострочный run (echo $GITHUB_SHA | head -c7) -хэш коммита в 7 символов
        run: |
          TAG_NAME=$(echo $GITHUB_SHA | head -c7)
          docker buildx create --use
          docker buildx build --no-cache --push --tag $REGISTRY/$IMAGE_NAME:$TAG_NAME -f backend/Dockerfile backend/ 

  deploy-image:
    runs-on: ubuntu-latest
    # выполняется только после выполнения image-build-and-push
    needs: image-build-and-push

    steps:
      - name: Checkout master
        uses: actions/checkout@v3

      - name: Copy docker-compose.yaml and nginx.conf to server
        # ssh-action с помощью которого мы сможем залезть на сервак
        uses: appleboy/scp-action@v1.0.0
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSHKEY }}
          source: "backend/docker-compose.yaml,backend/nginx.conf"
          target: "~/"
          strip_components: 1

      - name: Deploy to Selectel Cloud via SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSHKEY }}
          envs: IMAGE_NAME,REGISTRY,GITHUB_SHA,CONTAINER_NAME
          script: |
            # Set up variables
            TAG_NAME=$(echo $GITHUB_SHA | head -c7)
            
            # Login into Selectel Registry
            docker login -u ${{ secrets.REGISTRY_USERNAME }} -p ${{ secrets.REGISTRY_PASSWORD }} $REGISTRY
            
            # Navigate to the home directory
            cd ~/
            
            # Clear the .env file 
            > .env
            
            # Add secrets to the .env file (one by one)
            echo "JWT_SECRET=${{ secrets.JWT_SECRET }}" >> .env
            echo "ADMIN_EMAILS=${{ secrets.ADMIN_EMAILS }}" >> .env
            echo "DEEPSEEK_API_KEY=${{ secrets.DEEPSEEK_API_KEY }}" >> .env
            echo "DEEPSEEK_URL=${{ secrets.DEEPSEEK_URL }}" >> .env
            echo "DEEPSEEK_MODEL=${{ secrets.DEEPSEEK_MODEL }}" >> .env
            echo "ROLE_SYSTEM=${{ secrets.ROLE_SYSTEM }}" >> .env
            echo "ROLE_USER=${{ secrets.ROLE_USER }}" >> .env
            echo "EXTRACT=${{ secrets.EXTRACT }}" >> .env
            echo "GRAMMAR=${{ secrets.GRAMMAR }}" >> .env
            echo "ABOUT=${{ secrets.ABOUT }}" >> .env
            echo "EXPERIENCE=${{ secrets.EXPERIENCE }}" >> .env
            echo "SKILLS=${{ secrets.SKILLS }}" >> .env
            echo "POSTGRES_STR=${{ secrets.POSTGRES_STR }}" >> .env
            echo "POSTGRES_DB=${{ secrets.POSTGRES_DB }}" >> .env
            echo "POSTGRES_USER=${{ secrets.POSTGRES_USER }}" >> .env
            echo "POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}" >> .env
            
            # Shut down any running Docker containers
            docker-compose down
            
            # Update the backend image in the docker-compose.yaml to use the new image tag
            sed -i "s|build:.*|image: $REGISTRY/$IMAGE_NAME:$TAG_NAME|" docker-compose.yaml
            
            # Remove the build-related configurations from docker-compose.yaml
            sed -i "/dockerfile:/d" docker-compose.yaml
            sed -i "/context:/d" docker-compose.yaml
            
            # Pull the latest Docker images
            docker-compose pull
            
            # Start all services with the new configuration, force recreate containers
            docker-compose up -d --force-recreate